#######################################
############  usuário  ################
#######################################

# Criar usuário
POST http://127.0.0.1:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 1,
    "nome": "teste",
    "email": "teste@gmail.com",
    "senha": "1234"
}

######################
#######################################
# Pegar usuário
GET http://127.0.0.1:8000/usuario?id=1 HTTP/1.1
content-type: application/json


# Pegar usuário NOME
###############
GET http://127.0.0.1:8000/usuario/nome?nome=teste HTTP/1.1
content-type: application/json

#####

GET http://127.0.0.1:8000/usuario/1/endereco HTTP/1.1
content-type: application/json


#######################################
############  endereço  ###############
#######################################

# Criar endereço 1
POST http://127.0.0.1:8000/endereco/1 HTTP/1.1
content-type: application/json

{
    "id": "1",
    "rua": "Rua Ladrilhada",
    "cep": "99999-999",
    "cidade": "São Paulo",
    "estado": "SP"
}   

#######################################
############  produto  ################
#######################################

# Criar produto
POST http://127.0.0.1:8000/produto HTTP/1.1
content-type: application/json

{
    "id": 1,
    "nome": "Sorvete",
    "descricao": "Doce gelado",
    "preco": 9.99
}

###############
# CONSULTAR PRODUTO
GET http://127.0.0.1:8000/produto?id=1


##########
DELETE http://127.0.0.1:8000/usuario?id=1 HTTP/1.1
content-type: application/json


####################
# CRIAR O CARRINHO 
POST http://127.0.0.1:8000/carrinho/1/1 HTTP/1.1
content-type: application/json


########
# CONSULTAR VALOR DO CARRINHO
GET http://127.0.0.1:8000/carrinho/valor/1 HTTP/1.1
content-type: application/json

########
# RETORNAR O CARRINHO 
GET http://127.0.0.1:8000/carrinho/1 HTTP/1.1
content-type: application/json


###############
DELETE http://127.0.0.1:8000/produto/1



###############
DELETE http://127.0.0.1:8000/carrinho/1


###############
DELETE http://127.0.0.1:8000/usuario/1/endereco/1

